trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'build-tools/*'

jobs:

- job: curl
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 360
  strategy:
    matrix:
      'x86-64':
        IMAGE: "debian:7"
      'arm32v7':
        IMAGE: "arm32v7/debian:7"
      'arm64v8':
        IMAGE: "arm64v8/debian:8"

  steps:
  - script: |
      set -eu; set -o pipefail
      cd build-tools
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      Say --Reset-Stopwatch
      Say "qemu user static"
      # sudo apt-get install qemu-user-static -y -qq >/dev/null
      docker run --name qemu-user-static multiarch/qemu-user-static >/dev/null 2>&1 || true
      sudo docker cp qemu-user-static:/usr/bin/. /usr/bin
      /usr/bin/qemu-arm-static --version
      Say "Register qemu static"
      docker run --rm --privileged multiarch/qemu-user-static:register --reset >/dev/null 2>&1
      utils_fixed_url=https://raw.githubusercontent.com/devizer/NetCore.CaValidationLab/58e96809ba79e162b901095fad1c6555bb91b746/4gcc/build-gcc-utilities.sh
      utils_master_url=https://raw.githubusercontent.com/devizer/NetCore.CaValidationLab/master/4gcc/build-gcc-utilities.sh
      try-and-retry curl -kSL -o /tmp/build-gcc-utilities.sh "${utils_fixed_url}"
      CONTAINER="builder"
      docker pull "$IMAGE" >/dev/null
      docker run -d --sysctl net.ipv6.conf.all.disable_ipv6=1 --privileged --hostname "$CONTAINER" --name "$CONTAINER" -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static "$IMAGE" sh -c 'tail -f /dev/null'
      for f in /usr/local/bin/Say /usr/local/bin/try-and-retry; do
        docker cp $f "$CONTAINER":/usr/bin/.
      done
      for f in "$(pwd)/"*.sh /tmp/build-gcc-utilities.sh; do
        Say "copying $f to the container"
        docker cp "$f" "$CONTAINER":/root/.
      done

      docker exec -t -e GCCVER="${GCCVER:-}" -e SYSTEM_ARTIFACTSDIRECTORY="${SYSTEM_ARTIFACTSDIRECTORY:-}" $CONTAINER bash -e -c "cd /root; Say --Reset-Stopwatch; export DEBIAN_FRONTEND=noninteractive; source /root/build-gcc-utilities.sh; say_cpu_name; prepare_os; Say Ready; pwd; bash -e build-curl.sh"
    displayName: 'curl'

  - script: |
      set -eu; set -o pipefail
      Say "grab cmake artifacts"
      CONTAINER="builder"
      docker cp $CONTAINER:$SYSTEM_ARTIFACTSDIRECTORY/. "$SYSTEM_ARTIFACTSDIRECTORY"
      Say "Bye"
    condition: succeededOrFailed()
    displayName: 'grab artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'
