variables:
  QA: 42

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'postgres-lab/*'

jobs:

- job: PG
  pool:
    vmImage: '$(VM)'
  timeoutInMinutes: 30
  strategy:
    matrix:
      'Ubuntu 22.04': 
        VM: ubuntu-22.04
      'Ubuntu 20.04': 
        VM: ubuntu-20.04
      'Ubuntu 18.04': 
        VM: ubuntu-18.04

  steps:
  - bash: |
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      Say --Reset-Stopwatch
      Say "Install"
      sudo apt-get update -qq
      sudo apt-get install libecpg-dev -y -qq |& grep Setting
      sudo pip install pgsanity
      set -eu
      function check_sql() {
        echo "$1" > code.sql
        Say "pgsanity: '$(cat code.sql)'"
        err=none;
        pgsanity code.sql || err=$?
        echo "ERROR CODE IS [$err]"
      }
      check_sql "Select Version();"
      check_sql "Select AnError;"
      check_sql "Syntax Error;"
    displayName: 'pgsanity: install'


  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'
