variables:
    Project: 'Azure Pipelines Agent in Docker'
    OS: 'Linux'

jobs:

  - job: Build
    strategy:
      maxParallel: 5
      matrix:

        'Jessie 8':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie"
          TAG: jessie
          BASE_IMAGE: 'debian:jessie'

        'Stretch 9':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch"
          TAG: stretch
          BASE_IMAGE: 'debian:stretch'

        'Bullseye 11':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bullseye"
          TAG: bullseye
          BASE_IMAGE: 'debian:bullseye'

        'Buster 10':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster"
          TAG: buster
          BASE_IMAGE: 'debian:buster'

        'Xenial 16.04':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial"
          TAG: xenial
          BASE_IMAGE: 'ubuntu:xenial'

        'Bionic 18.04':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic"
          TAG: bionic
          BASE_IMAGE: 'ubuntu:bionic'
          
        'Focal 20.04':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal -t devizervlad/crossplatform-azure-pipelines-agent:latest"
          TAG: focal
          BASE_IMAGE: 'ubuntu:focal'

        'Slim Jessie 8':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie-slim"
          TAG: jessie-slim
          BASE_IMAGE: 'debian:jessie'
          SLIM: 'true'

        'Slim Bullseye 11':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bullseye"
          TAG: bullseye-slim
          BASE_IMAGE: 'debian:bullseye'
          SLIM: 'true'

        'Slim Focal 20.04':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal-slim -t devizervlad/crossplatform-azure-pipelines-agent:latest-slim"
          TAG: focal-slim
          BASE_IMAGE: 'ubuntu:focal'
          SLIM: 'true'
          
        'Slim Buster 10':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster-slim"
          TAG: buster-slim
          BASE_IMAGE: 'debian:buster'
          SLIM: 'true'

        'Slim Stretch 9':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch-slim"
          TAG: stretch-slim
          BASE_IMAGE: 'debian:stretch'
          SLIM: 'true'

        'Slim Bionic 18.04':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic-slim"
          TAG: bionic-slim
          BASE_IMAGE: 'ubuntu:bionic'
          SLIM: 'true'

        'Slim Xenial 16.04':
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial-slim"
          TAG: xenial-slim
          BASE_IMAGE: 'ubuntu:xenial'
          SLIM: 'true'

    timeoutInMinutes: 300
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-nix.yml

# trigger:
#  - master

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - 'build-tools/*'
    - 'azure-pipelines-build-tools.yml'
      
#schedules:
#  - cron: "30 3 * * *"
#    displayName: 'Nightly rebuild (at 3:30)'
#    branches:
#      include:
#        - master
