variables:
  QA: 42

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'postgres-lab/*'

jobs:

- job: PG
  pool:
    vmImage: '$(VM)'
  timeoutInMinutes: 30
  strategy:
    matrix:
      'Ubuntu 22.04': 
        VM: ubuntu-22.04
      'Ubuntu 20.04': 
        VM: ubuntu-20.04
      'Ubuntu 18.04': 
        VM: ubuntu-18.04

  steps:
  - bash: |
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      Say --Reset-Stopwatch
      Say "Install"
      sudo apt-get update -qq
      sudo apt-get install libecpg-dev -y -qq |& grep Setting
      sudo pip install pgsanity
      pgsanity -h
      set -eu
      echo 'Select Version();' >> Normal.sql
      echo 'Syntax Error;' >> Error.sql
      Say "Check up Normal.sql [Select Version();]"
      pgsanity Normal.sql
      Say "Check up Error.sql [Syntax Error;]"
      err=none;
      pgsanity Error.sql || err=$?
      echo "EXIT CODE IS [$err]"
    displayName: 'pgsanity: install'


  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'
