trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'build-tools/Prepare-proot.sh'

jobs:
- job: Prepare
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 360


  steps:
  - script: |
        cd build-tools
        bash -e Prepare-proot.sh
    displayName: 'Run a multi-line script'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: 'Deploy-it-by-$(Agent.JobName)'
