variables:
    Project: 'Azure Pipelines Agent in Docker'
    OS: 'Linux'

jobs:

  - job: Build
    strategy:
      maxParallel: 6
      matrix:

        Jessie_8_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie"
          TAG: jessie-slim
          BASE_IMAGE: 'debian:jessie'

        Stretch_9_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch"
          TAG: stretch
          BASE_IMAGE: 'debian:stretch'

        Bullseye_11_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bullseye"
          TAG: bullseye
          BASE_IMAGE: 'debian:bullseye'

        Buster_10_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster"
          TAG: buster
          BASE_IMAGE: 'debian:buster'

        Xenial_16_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial"
          TAG: xenial
          BASE_IMAGE: 'ubuntu:xenial'

        Bionic_18_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic"
          TAG: bionic
          BASE_IMAGE: 'ubuntu:bionic'
          
        Focal_20_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal -t devizervlad/crossplatform-azure-pipelines-agent:latest"
          TAG: focal
          BASE_IMAGE: 'ubuntu:focal'

        Slim_Jessie_8_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie-slim"
          TAG: jessie
          BASE_IMAGE: 'debian:jessie'
          SLIM: 'true'

        Slim_Bullseye_11_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bullseye"
          TAG: bullseye-slim
          BASE_IMAGE: 'debian:bullseye'
          SLIM: 'true'

        Slim_Focal_20_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal-slim -t devizervlad/crossplatform-azure-pipelines-agent:latest-slim"
          TAG: focal-slim
          BASE_IMAGE: 'ubuntu:focal'
          SLIM: 'true'
          
        Slim_Buster_10_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster-slim"
          TAG: buster-slim
          BASE_IMAGE: 'debian:buster'
          SLIM: 'true'

        Slim_Stretch_9_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch-slim"
          TAG: stretch-slim
          BASE_IMAGE: 'debian:stretch'
          SLIM: 'true'


        Slim_Bionic_18_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic-slim"
          TAG: bionic-slim
          BASE_IMAGE: 'ubuntu:bionic'
          SLIM: 'true'

        Slim_Xenial_16_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial-slim"
          TAG: xenial-slim
          BASE_IMAGE: 'ubuntu:xenial'
          SLIM: 'true'

    timeoutInMinutes: 300
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-nix.yml

# trigger:
#  - master

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - 'build-tools/*'
    - 'azure-pipelines-build-tools.yml'
      
#schedules:
#  - cron: "30 3 * * *"
#    displayName: 'Nightly rebuild (at 3:30)'
#    branches:
#      include:
#        - master
