trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'build-tools/Prepare-proot.sh'

jobs:
- job: Prepare
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 360
  strategy:
    matrix:
      'FULL':
        PREPARE_OS_MODE: "BIG"
        XZ: ""
      'MICRO':
        PREPARE_OS_MODE: "MICRO"
        XZ: "-micro"

  steps:
  - script: |
        set -e
        cd build-tools
        sudo bash -c "export SYSTEM_ARTIFACTSDIRECTORY=$SYSTEM_ARTIFACTSDIRECTORY; bash -e Prepare-proot.sh"
        sudo chown -R $(whoami) $SYSTEM_ARTIFACTSDIRECTORY
    displayName: 'Batch of images'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: 'Deploy-it-by-$(Agent.JobName)'
