ARG BASE_IMAGE=debian:jessie
FROM ${BASE_IMAGE}
ARG BASE_IMAGE
RUN echo "Building on image: ${BASE_IMAGE}"
RUN if [ -n "$(command -v apk)" ]; then apk update; apk update || apk update || apk update; cmd="apk add bash wget libstdc++"; eval $cmd || eval $cmd || eval $cmd; fi

WORKDIR /Work
COPY . .
SHELL ["/bin/bash", "-eu", "-o", "pipefail", "-c"]

RUN bash install-build-tools-bundle.sh; bash Install-DevOps-Library.sh; Repair-Legacy-OS-Sources
RUN if [[ -n "$(command -v apt-get)" ]]; then try-and-retry apt-get install wget -qq; fi

RUN \
  Say "Get-NET-RID - [$(Get-NET-RID)]"; \
  Say "Get-Linux-OS-ID - [$(Get-Linux-OS-ID)]"; \
  Say "Get-Linux-OS-Architecture - [$(Get-Linux-OS-Architecture)]"


CMD ["bash"]
