#!/usr/bin/env bash
function get1stline() {
  eval "$1" >/tmp/.a-log
  cat /tmp/.a-log | head -1
  rm -f /tmp/.a-log
}

libssl=$(apt-cache search libssl | grep -E '^libssl[\.0-9]* ' | awk '{print $1}' | sed ':a;N;$!ba;s/\n/, /g') 
sqlite=$(sqlite3 --version | awk '{print $1 ", " $2 " " $3}')
dpl=$(gem list dpl  | grep dpl | sed ':a;N;$!ba;s/\n/, /g')
echo "Base Image:     ${BASE_DOCKER_IMAGE}
dotnet sdk:     $(dotnet --list-sdks | awk '{print $1}' | sed ':a;N;$!ba;s/\n/, /g')
mono:           $(mono --version | head -1)
xunit.console:  $(get1stline  xunit.console)
nunit3-console: $(get1stline 'nunit3-console --version')
node:           $(node --version)
npm:            $(npm --version)
yarn:           $(yarn --version)
openssl:        $(openssl version)
libssl:         $libssl
git:            $(git --version)
docker:         $(docker --version)
docker-compose: $(docker-compose --version), $(docker-compose version | grep OpenSSL)
python3:        $(python3 --version)
pip3:           $(pip3 --version)
pwsh:           $(pwsh --version)
bash:           $BASH_VERSION
sqlite3 shell:  $sqlite
mysql client:   $(mysql --version)
psql client:    $(psql --version)
ruby:           $(ruby --version)
gem:            $(gem --version)
deploy tools:   $dpl
"
