#!/usr/bin/env bash
function get1stline() {
  eval "$1" >/tmp/.a-log
  cat /tmp/.a-log | head -1
  rm -f /tmp/.a-log
}

source /pre-configure/env.sh

libssl=$(apt-cache search libssl 2>/dev/null| grep -E '^libssl[\.0-9]* ' | awk '{print $1}' | sed ':a;N;$!ba;s/\n/, /g') 
libgdiplus=$(apt-cache policy libgdiplus 2>/dev/null | grep -E '(I|i)nstalled' | awk '{print $NF}') 
sqlite=$(sqlite3 --version 2>/dev/null | awk '{print $1 ", " $2 " " $3}')
dpl=$(gem list dpl 2>/dev/null  | grep dpl | sed ':a;N;$!ba;s/\n/, /g')
build_date="$(date --utc '+%F %T %Z')"; 

echo "\
  Build date:     $build_date
  Base Image:     $BASE_DOCKER_IMAGE
  Commit:         $BUILD_SOURCEVERSION
  Branch:         $BUILD_SOURCEBRANCHNAME
  Build Id:       $BUILD_BUILDID
  Build Url:      $BUILD_URL
  Job Url:        $JOB_URL
* dotnet sdk:     $(dotnet --list-sdks 2>/dev/null | awk '{print $1}' | sed ':a;N;$!ba;s/\n/, /g')
* pwsh:           $(pwsh --version 2>/dev/null)
* mono:           $(mono --version 2>/dev/null | head -1)
* msbuild:        $(msbuild /nologo /version)
* nuget:          $(get1stline nuget)
* paket:          $(paket --version 2>/dev/null)
* libgdiplus:     $libgdiplus
* xunit.console:  $(get1stline  xunit.console)
* nunit3-console: $(get1stline 'nunit3-console --version')
* node:           $(node --version 2>/dev/null)
* npm:            $(npm --version 2>/dev/null)
* yarn:           $(yarn --version 2>/dev/null)
  openssl:        $(openssl version 2>/dev/null)
  libssl:         $libssl
* git:            $(git --version 2>/dev/null)
* git lfs:        $(git-lfs --version 2>/dev/null)
* docker:         $(docker --version 2>/dev/null)
* docker-compose: $(docker-compose --version 2>/dev/null), $(docker-compose version  2>/dev/null| grep OpenSSL)
* go:             $(go version 2>/dev/null)
  python3:        $(python3 --version 2>/dev/null)
  pip3:           $(pip3 --version 2>/dev/null)
  pip:            $(pip --version 2>/dev/null)
  bash:           $BASH_VERSION
* sqlite3 shell:  $sqlite
  mysql client:   $(mysql --version 2>/dev/null)
  psql client:    $(psql --version 2>/dev/null)
  ruby:           $(ruby --version 2>/dev/null)
  gem:            $(gem --version 2>/dev/null)
* deploy tools:   $dpl

Packages marked by asterisk are distribution independent for debian and its derivatives
"

# TODO: just uncomment rm -f *.core || true